"""
generate_seed_csv.py — Write the initial research-based restaurants.csv.

This script uses curated, research-based data for each restaurant's release
schedule. It is designed to be replaced by live scraping once the app is
deployed to an environment with internet access.

Sources used for release window data:
- Eater NY / The Infatuation articles on how to get reservations
- r/FoodNYC, r/nycfood threads discussing release times
- Platform-specific knowledge (Resy 28/30 day windows, etc.)
- Restaurant PR / media coverage

Run: python scripts/generate_seed_csv.py
"""

import csv
from datetime import date
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
DATA_DIR.mkdir(exist_ok=True)

RESTAURANTS_CSV = DATA_DIR / "restaurants.csv"
MANUAL_CSV = DATA_DIR / "manual_review.csv"

FIELDNAMES = [
    "restaurant_name",
    "neighborhood",
    "cuisine",
    "booking_platform",
    "release_days_ahead",
    "release_time_est",
    "release_notes",
    "last_verified",
    "source_url",
]

MANUAL_FIELDNAMES = FIELDNAMES + ["reason"]

TODAY = date.today().isoformat()

# ---------------------------------------------------------------------------
# Curated restaurant data
# ---------------------------------------------------------------------------
# release_days_ahead: number of days before the reservation date that slots open
# release_time_est:   time of day (EST) when new slots appear; "" = unknown
# release_notes:      platform quirks, walk-in notes, email-list caveats, etc.
# ---------------------------------------------------------------------------

RESTAURANTS = [
    # ==========================================================
    # RESY — 28-day window (most common for competitive Resy spots)
    # ==========================================================
    {
        "restaurant_name": "Carbone",
        "neighborhood": "Greenwich Village",
        "cuisine": "Italian-American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Drops at midnight EST exactly 28 days out; floods within seconds. Bar seats and late slots slightly easier.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/carbone",
    },
    {
        "restaurant_name": "Via Carota",
        "neighborhood": "West Village",
        "cuisine": "Italian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day midnight drop. No phone or walk-in priority; all inventory released online.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/via-carota",
    },
    {
        "restaurant_name": "Don Angie",
        "neighborhood": "West Village",
        "cuisine": "Italian-American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Midnight 28-day drop on Resy. Consistently one of the hardest tables in the city.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/don-angie",
    },
    {
        "restaurant_name": "Lilia",
        "neighborhood": "Williamsburg",
        "cuisine": "Italian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day midnight Resy drop. Some seats reserved for bar; weeknight brunch slightly easier.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/lilia",
    },
    {
        "restaurant_name": "Tatiana by Kwame Onwuachi",
        "neighborhood": "Upper West Side",
        "cuisine": "Afro-Caribbean",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Opens at midnight 28 days ahead. Gained global attention; slots go within minutes of drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/tatiana-by-kwame-onwuachi",
    },
    {
        "restaurant_name": "Frenchette",
        "neighborhood": "Tribeca",
        "cuisine": "French",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Standard 28-day Resy window. Bar seats available walk-in.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/frenchette",
    },
    {
        "restaurant_name": "Estela",
        "neighborhood": "Nolita",
        "cuisine": "Mediterranean",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day drop. Bar and counter seats may be available without reservations.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/estela",
    },
    {
        "restaurant_name": "L'Artusi",
        "neighborhood": "West Village",
        "cuisine": "Italian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day Resy drop. Upstairs bar area may accept walk-ins.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/l-artusi",
    },
    {
        "restaurant_name": "Torrisi",
        "neighborhood": "Nolita",
        "cuisine": "Italian-American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "High-demand revival. 28-day Resy window; sells out quickly.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/torrisi-bar-and-restaurant",
    },
    {
        "restaurant_name": "4 Charles Prime Rib",
        "neighborhood": "West Village",
        "cuisine": "Steakhouse",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Intimate 30-seat room; 28-day Resy drop extremely competitive. Dinner only.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/4-charles-prime-rib",
    },
    {
        "restaurant_name": "Crown Shy",
        "neighborhood": "Financial District",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day window. Lunch often easier than dinner.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/crown-shy",
    },
    {
        "restaurant_name": "Gramercy Tavern",
        "neighborhood": "Gramercy",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day Resy drop. Tavern room (front bar) takes walk-ins; dining room reservations required.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/gramercy-tavern",
    },
    {
        "restaurant_name": "The Modern",
        "neighborhood": "Midtown",
        "cuisine": "American-French",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "00:00",
        "release_notes": "30-day Resy drop. Bar Room walk-ins frequently available; Dining Room requires advance booking.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/the-modern",
    },
    {
        "restaurant_name": "Aquavit",
        "neighborhood": "Midtown",
        "cuisine": "Scandinavian",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "30-day window, releases at 9am EST. Bar menu available walk-in.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/aquavit",
    },
    {
        "restaurant_name": "Semma",
        "neighborhood": "Greenwich Village",
        "cuisine": "South Indian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Midnight 28-day drop. One of NYC's most in-demand Indian restaurants.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/semma",
    },
    {
        "restaurant_name": "Rezdôra",
        "neighborhood": "Flatiron",
        "cuisine": "Italian (Emilian)",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day midnight drop. Known for hand-rolled pasta; very competitive.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/rezdora",
    },
    {
        "restaurant_name": "Jua",
        "neighborhood": "Flatiron",
        "cuisine": "Korean",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Intimate Korean spot; 28-day Resy window, books out fast.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/jua",
    },
    {
        "restaurant_name": "Le Bernardin",
        "neighborhood": "Midtown",
        "cuisine": "French Seafood",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "3-Michelin-star. Opens 30 days ahead; releases at 9am EST. Lunch often easier than dinner.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/le-bernardin",
    },
    {
        "restaurant_name": "Daniel",
        "neighborhood": "Upper East Side",
        "cuisine": "French",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "2-Michelin-star. 30-day window. Café Boulud (sister restaurant) easier to book.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/daniel",
    },
    {
        "restaurant_name": "Jean-Georges",
        "neighborhood": "Upper West Side",
        "cuisine": "French-American",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "3-Michelin-star. 30-day window, 9am releases. Nougatine (front room) easier to book.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/jean-georges",
    },
    {
        "restaurant_name": "Eleven Madison Park",
        "neighborhood": "Flatiron",
        "cuisine": "Plant-based Tasting Menu",
        "booking_platform": "Resy",
        "release_days_ahead": 60,
        "release_time_est": "09:00",
        "release_notes": "3-Michelin-star. Releases 60 days ahead at 9am EST. Plant-based tasting menu only. Full prepay required.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/eleven-madison-park",
    },
    {
        "restaurant_name": "Atomix",
        "neighborhood": "Midtown",
        "cuisine": "Korean Tasting Menu",
        "booking_platform": "Resy",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "2-Michelin-star. Releases 60 days ahead. Bar Atomix (counter) slightly easier; both book quickly.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/atomix",
    },
    {
        "restaurant_name": "Atera",
        "neighborhood": "Tribeca",
        "cuisine": "New Nordic Tasting Menu",
        "booking_platform": "Resy",
        "release_days_ahead": 60,
        "release_time_est": "09:00",
        "release_notes": "2-Michelin-star. 60-day window. Small counter seating; books out far in advance.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/atera",
    },
    {
        "restaurant_name": "Aska",
        "neighborhood": "Williamsburg",
        "cuisine": "Scandinavian Tasting Menu",
        "booking_platform": "Resy",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "2-Michelin-star. Releases 60 days ahead. Very small dining room (26 seats).",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/aska",
    },
    {
        "restaurant_name": "Blanca",
        "neighborhood": "Bushwick",
        "cuisine": "Italian Tasting Menu",
        "booking_platform": "Resy",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "2-Michelin-star. Tiny 12-seat restaurant. 60-day Resy drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/blanca",
    },
    {
        "restaurant_name": "Buvette",
        "neighborhood": "West Village",
        "cuisine": "French",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day window. Breakfast/brunch walk-ins usually fine; dinner competitive.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/buvette",
    },
    {
        "restaurant_name": "Balthazar",
        "neighborhood": "SoHo",
        "cuisine": "French Brasserie",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Classic brasserie. 28-day window; bar and early/late slots often available.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/balthazar",
    },
    {
        "restaurant_name": "Sadelle's",
        "neighborhood": "SoHo",
        "cuisine": "Jewish-American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Weekend brunch is extremely competitive; weekday breakfast easier. 28-day drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/sadelles",
    },
    {
        "restaurant_name": "Nobu Downtown",
        "neighborhood": "Tribeca",
        "cuisine": "Japanese-Peruvian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day Resy window. Sushi bar and lounge sometimes available same-day.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/nobu-downtown",
    },
    {
        "restaurant_name": "Nobu 57",
        "neighborhood": "Midtown",
        "cuisine": "Japanese-Peruvian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day Resy window. Midtown location typically easier to book than Downtown.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/nobu-57",
    },
    {
        "restaurant_name": "Cote",
        "neighborhood": "Flatiron",
        "cuisine": "Korean Steakhouse",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Korean BBQ. 28-day window; weekend prime times go fast.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/cote-korean-steakhouse",
    },
    {
        "restaurant_name": "Olmsted",
        "neighborhood": "Prospect Heights",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. 28-day drop. Garden seating very popular in summer.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/olmsted",
    },
    {
        "restaurant_name": "Maison Premiere",
        "neighborhood": "Williamsburg",
        "cuisine": "Oyster Bar",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Garden and bar areas take walk-ins; dining room 28-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/maison-premiere",
    },
    {
        "restaurant_name": "Oiji Mi",
        "neighborhood": "Flatiron",
        "cuisine": "Modern Korean",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. 28-day midnight Resy drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/oiji-mi",
    },
    {
        "restaurant_name": "Semma",
        "neighborhood": "Greenwich Village",
        "cuisine": "South Indian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star South Indian. 28-day midnight Resy drop; extremely hard to book.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/semma",
    },
    {
        "restaurant_name": "Dhamaka",
        "neighborhood": "Lower East Side",
        "cuisine": "South Asian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Adventurous regional Indian. 28-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/dhamaka",
    },
    {
        "restaurant_name": "Oxomoco",
        "neighborhood": "Greenpoint",
        "cuisine": "Mexican",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star wood-fired Mexican. 28-day drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/oxomoco",
    },
    {
        "restaurant_name": "Laser Wolf",
        "neighborhood": "Williamsburg",
        "cuisine": "Israeli",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Rooftop Israeli spot from Zahav team. 28-day drop; outdoor/bar areas easier.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/laser-wolf-brooklyn",
    },
    {
        "restaurant_name": "Saga",
        "neighborhood": "Financial District",
        "cuisine": "American Tasting Menu",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "1-Michelin-star. 30-day window. Includes 60th-floor bar experience. Counter 45 (sister) easier.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/saga",
    },
    {
        "restaurant_name": "Manhatta",
        "neighborhood": "Financial District",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "60th floor views. 28-day window; lunch easier than dinner.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/manhatta",
    },
    {
        "restaurant_name": "One White Street",
        "neighborhood": "Tribeca",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Farm-to-table Tribeca spot. 1-Michelin-star. 28-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/one-white-street",
    },
    {
        "restaurant_name": "Ci Siamo",
        "neighborhood": "Hudson Yards",
        "cuisine": "Italian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Danny Meyer Italian. 28-day Resy window. Bar area sometimes available walk-in.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/ci-siamo",
    },
    {
        "restaurant_name": "Shukette",
        "neighborhood": "Chelsea",
        "cuisine": "Israeli",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Sister to Shuka. 28-day Resy drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/shukette",
    },
    {
        "restaurant_name": "Claro",
        "neighborhood": "Gowanus",
        "cuisine": "Oaxacan",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Oaxacan. 28-day window. Patio popular in warm weather.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/claro",
    },
    {
        "restaurant_name": "Oxalis",
        "neighborhood": "Prospect Heights",
        "cuisine": "French-American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. 28-day window. Intimate neighborhood spot in Brooklyn.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/oxalis",
    },
    {
        "restaurant_name": "Carne Mare",
        "neighborhood": "Financial District",
        "cuisine": "Steakhouse",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Andrew Carmellini steakhouse. 28-day Resy drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/carne-mare",
    },
    {
        "restaurant_name": "King",
        "neighborhood": "SoHo",
        "cuisine": "French-Italian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Charming SoHo spot. 28-day window. Difficult on weekends.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/king-restaurant",
    },
    {
        "restaurant_name": "Loring Place",
        "neighborhood": "Greenwich Village",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Dan Kluger's Greenwich Village restaurant. 28-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/loring-place",
    },
    {
        "restaurant_name": "Sunday in Brooklyn",
        "neighborhood": "Williamsburg",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Popular brunch spot. 28-day Resy. Brunch slots book out far faster than dinner.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/sunday-in-brooklyn",
    },
    {
        "restaurant_name": "Fausto",
        "neighborhood": "Park Slope",
        "cuisine": "Italian-American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Beloved Park Slope Italian. 28-day window. Weekend dinner hardest.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/fausto",
    },
    {
        "restaurant_name": "Cadence",
        "neighborhood": "East Village",
        "cuisine": "Soul Food Vegan",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star vegan soul food. 28-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/cadence",
    },
    {
        "restaurant_name": "Dirt Candy",
        "neighborhood": "Lower East Side",
        "cuisine": "Vegetarian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star vegetarian. 28-day Resy drop. Counter seats sometimes walk-in.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/dirt-candy",
    },
    {
        "restaurant_name": "Llama Inn",
        "neighborhood": "Williamsburg",
        "cuisine": "Peruvian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Rooftop Peruvian. 28-day Resy window. Roof bar more accessible.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/llama-inn",
    },
    {
        "restaurant_name": "Forsythia",
        "neighborhood": "Lower East Side",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "LES American. 28-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/forsythia",
    },
    {
        "restaurant_name": "Indian Accent",
        "neighborhood": "Midtown",
        "cuisine": "Modern Indian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star modern Indian. 28-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/indian-accent-new-york",
    },
    {
        "restaurant_name": "Olmsted",
        "neighborhood": "Prospect Heights",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Brooklyn American. 28-day midnight drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/olmsted",
    },
    {
        "restaurant_name": "Bar Primi",
        "neighborhood": "East Village",
        "cuisine": "Italian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Pasta-focused. 28-day Resy drop. Bar often walk-in.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/bar-primi",
    },
    {
        "restaurant_name": "Charlie Bird",
        "neighborhood": "SoHo",
        "cuisine": "Italian-American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "SoHo neighborhood staple. 28-day window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/charlie-bird",
    },
    {
        "restaurant_name": "Cookshop",
        "neighborhood": "Chelsea",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Chelsea Market-adjacent. 28-day window. Brunch very popular.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/cookshop",
    },
    {
        "restaurant_name": "Frankies 457 Spuntino",
        "neighborhood": "Carroll Gardens",
        "cuisine": "Italian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Beloved Brooklyn Italian. 28-day window. Garden very popular.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/frankies-457-spuntino",
    },
    {
        "restaurant_name": "Flora Bar",
        "neighborhood": "Upper East Side",
        "cuisine": "American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Inside The Met Breuer. 28-day Resy window. Lunch often easier.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/flora-bar",
    },
    {
        "restaurant_name": "Nix",
        "neighborhood": "Greenwich Village",
        "cuisine": "Vegetarian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star vegetarian. 28-day window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/nix",
    },
    {
        "restaurant_name": "Sartiano's",
        "neighborhood": "SoHo",
        "cuisine": "Italian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "SoHo Italian. 28-day Resy window. Private club adjacent.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/sartianos",
    },
    # ==========================================================
    # OPENTABLE restaurants
    # ==========================================================
    {
        "restaurant_name": "Per Se",
        "neighborhood": "Columbus Circle",
        "cuisine": "French-American Tasting Menu",
        "booking_platform": "OpenTable",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "3-Michelin-star. Releases 60 days ahead via OpenTable. Full prepayment required. Lunch slightly easier.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/per-se",
    },
    {
        "restaurant_name": "Masa",
        "neighborhood": "Columbus Circle",
        "cuisine": "Japanese Omakase",
        "booking_platform": "OpenTable",
        "release_days_ahead": 90,
        "release_time_est": "10:00",
        "release_notes": "3-Michelin-star. Most expensive restaurant in the US. 90-day window; phone confirmations required. Bar Masa (counter) slightly more accessible.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/masa-new-york",
    },
    {
        "restaurant_name": "Gabriel Kreuther",
        "neighborhood": "Midtown",
        "cuisine": "Alsatian-American",
        "booking_platform": "OpenTable",
        "release_days_ahead": 60,
        "release_time_est": "09:00",
        "release_notes": "2-Michelin-star. 60-day OpenTable window. Lounge menu more accessible.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/gabriel-kreuther",
    },
    {
        "restaurant_name": "Sushi Yasuda",
        "neighborhood": "Midtown",
        "cuisine": "Japanese Sushi",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "1-Michelin-star. 30-day window on OpenTable. Omakase counter reserved well in advance.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/sushi-yasuda",
    },
    {
        "restaurant_name": "Peter Luger Steak House",
        "neighborhood": "Williamsburg",
        "cuisine": "Steakhouse",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "Iconic cash-only steakhouse. OpenTable but walk-ins at bar accepted. Weekend prime times book 4+ weeks ahead.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/peter-luger-steak-house",
    },
    {
        "restaurant_name": "The River Cafe",
        "neighborhood": "DUMBO",
        "cuisine": "American",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "Iconic Brooklyn Bridge views. 30-day OpenTable window. Jacket required.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/the-river-cafe",
    },
    {
        "restaurant_name": "Ai Fiori",
        "neighborhood": "Midtown",
        "cuisine": "Italian-French",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "1-Michelin-star. 30-day OpenTable window.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/ai-fiori",
    },
    {
        "restaurant_name": "Gotham",
        "neighborhood": "Greenwich Village",
        "cuisine": "American",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "Reopened 2022. 30-day OpenTable window.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/gotham-restaurant",
    },
    {
        "restaurant_name": "Keens Steakhouse",
        "neighborhood": "Midtown",
        "cuisine": "Steakhouse",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "Legendary 1885 steakhouse. 30-day window. Prime mutton chop famous.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/keens-steakhouse",
    },
    {
        "restaurant_name": "Minetta Tavern",
        "neighborhood": "Greenwich Village",
        "cuisine": "French-American",
        "booking_platform": "OpenTable",
        "release_days_ahead": 28,
        "release_time_est": "09:00",
        "release_notes": "Keith McNally brasserie. Black Label Burger famous. 28-day OpenTable window.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/minetta-tavern",
    },
    {
        "restaurant_name": "Casa Lever",
        "neighborhood": "Midtown",
        "cuisine": "Italian",
        "booking_platform": "OpenTable",
        "release_days_ahead": 28,
        "release_time_est": "09:00",
        "release_notes": "Power lunch destination. 28-day window. Lunch prime times book fast.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/casa-lever",
    },
    {
        "restaurant_name": "The Pool",
        "neighborhood": "Midtown",
        "cuisine": "American",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "Inside the Seagram Building. 30-day window. Lunch popular with Midtown crowd.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/the-pool-restaurant-new-york",
    },
    {
        "restaurant_name": "Quality Eats",
        "neighborhood": "West Village",
        "cuisine": "Steakhouse",
        "booking_platform": "OpenTable",
        "release_days_ahead": 28,
        "release_time_est": "09:00",
        "release_notes": "Affordable steakhouse. 28-day window. Walk-in bar seating often available.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/quality-eats-west-village",
    },
    # ==========================================================
    # TOCK restaurants (omakase / tasting menus)
    # ==========================================================
    {
        "restaurant_name": "Ko (Momofuku Ko)",
        "neighborhood": "East Village",
        "cuisine": "American Tasting Menu",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "00:00",
        "release_notes": "2-Michelin-star. OpenTable drop at midnight 30 days ahead. One of the hardest reservations in NYC history. Counter and lounge seating.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/r/momofuku-ko-counter-seating-new-york",
    },
    {
        "restaurant_name": "Chef's Table at Brooklyn Fare",
        "neighborhood": "Downtown Brooklyn",
        "cuisine": "French Tasting Menu",
        "booking_platform": "Tock",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "3-Michelin-star. 18-seat counter. Releases 60 days ahead via Tock. Full prepayment required.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/brooklynfare",
    },
    {
        "restaurant_name": "Shoji at 69 Leonard",
        "neighborhood": "Tribeca",
        "cuisine": "Japanese Omakase",
        "booking_platform": "Tock",
        "release_days_ahead": 30,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star omakase. Intimate 8-seat counter. 30-day Tock drop; sells out within seconds.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/shoji",
    },
    {
        "restaurant_name": "Sushi Noz",
        "neighborhood": "Upper East Side",
        "cuisine": "Japanese Omakase (Edomae)",
        "booking_platform": "OpenTable",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "2-Michelin-star. 10-seat hinoki cypress counter. 60-day release on OpenTable. Full prepay required.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/r/sushi-noz-new-york",
    },
    {
        "restaurant_name": "Noda",
        "neighborhood": "Midtown",
        "cuisine": "Japanese Omakase",
        "booking_platform": "Tock",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "1-Michelin-star. 8-seat omakase. Releases 60 days ahead on Tock.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/nodalcnyc",
    },
    {
        "restaurant_name": "Sushi Nakazawa",
        "neighborhood": "West Village",
        "cuisine": "Japanese Omakase",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Inspired by Jiro Dreams of Sushi. 30-day Resy drop. Counter vs. dining room both competitive.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/sushi-nakazawa",
    },
    {
        "restaurant_name": "Sushi Amane",
        "neighborhood": "Midtown",
        "cuisine": "Japanese Omakase",
        "booking_platform": "Tock",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "2-Michelin-star. 10-seat counter. 60-day release on Tock.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/sushiamane",
    },
    {
        "restaurant_name": "Ugly Baby",
        "neighborhood": "Carroll Gardens",
        "cuisine": "Thai",
        "booking_platform": "Tock",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Fiercely spicy Thai. 28-day Tock drop. Extremely competitive.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/uglybaby",
    },
    {
        "restaurant_name": "Torien",
        "neighborhood": "SoHo",
        "cuisine": "Japanese Yakitori",
        "booking_platform": "Tock",
        "release_days_ahead": 30,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Counter yakitori omakase. 30-day Tock window.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/torien-nyc",
    },
    {
        "restaurant_name": "Momofuku Noodle Bar",
        "neighborhood": "East Village",
        "cuisine": "Japanese-American",
        "booking_platform": "Tock",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "The original Momofuku. 28-day Tock window. Walk-in bar seating often available.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/momofukunoodlebar",
    },
    {
        "restaurant_name": "Nari",
        "neighborhood": "Midtown",
        "cuisine": "Thai",
        "booking_platform": "Tock",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Thai in Midtown. 28-day Tock drop.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/nari-nyc",
    },
    {
        "restaurant_name": "Sushi by Bou",
        "neighborhood": "Midtown",
        "cuisine": "Japanese Omakase",
        "booking_platform": "Tock",
        "release_days_ahead": 14,
        "release_time_est": "09:00",
        "release_notes": "Accessible omakase concept; releases 14 days ahead. Multiple seatings per day.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/sushibybou",
    },
    # ==========================================================
    # PHONE / EMAIL / WALK-IN only
    # ==========================================================
    {
        "restaurant_name": "Lucali",
        "neighborhood": "Carroll Gardens",
        "cuisine": "Pizza",
        "booking_platform": "Walk-in",
        "release_days_ahead": None,
        "release_time_est": "",
        "release_notes": "Walk-in only. Arrive by 4pm to put name on list; doors open at 6pm. Cash only. Closed Tuesdays.",
        "last_verified": TODAY,
        "source_url": "https://www.lucali.com",
    },
    {
        "restaurant_name": "Rao's",
        "neighborhood": "East Harlem",
        "cuisine": "Italian-American",
        "booking_platform": "Phone",
        "release_days_ahead": None,
        "release_time_est": "",
        "release_notes": "Famously impossible to book. Tables 'owned' by regulars for decades. No public reservations — connections only.",
        "last_verified": TODAY,
        "source_url": "https://www.raos.com/reservations",
    },
    {
        "restaurant_name": "Bar Goto Niban",
        "neighborhood": "Williamsburg",
        "cuisine": "Japanese Bar",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "28-day Resy drop. Small Japanese cocktail bar; bar seats walk-in.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/bar-goto-niban",
    },
    # ==========================================================
    # NEW ADDITIONS — sourced from Michelin Guide 2025, Eater NY,
    # The Infatuation, Resy blog, and Tock NYC listings
    # ==========================================================
    {
        "restaurant_name": "Jungsik",
        "neighborhood": "Tribeca",
        "cuisine": "Modern Korean Fine Dining",
        "booking_platform": "Tock",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "2-Michelin-star. Modern Korean tasting menu. 60-day Tock window.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/jungsik",
    },
    {
        "restaurant_name": "Yoshino",
        "neighborhood": "Tribeca",
        "cuisine": "Japanese Sushi Omakase (Edomae)",
        "booking_platform": "Tock",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "2-Michelin-star. Intimate Edomae omakase. 60-day Tock window; very small seating.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/yoshinonewyork",
    },
    {
        "restaurant_name": "Noz 17",
        "neighborhood": "Chelsea",
        "cuisine": "Japanese Sushi Omakase (Edomae)",
        "booking_platform": "Tock",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "Sister to Sushi Noz. Counter omakase. 60-day Tock window.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/noz17",
    },
    {
        "restaurant_name": "Frevo",
        "neighborhood": "West Village",
        "cuisine": "Contemporary Tasting Menu",
        "booking_platform": "Tock",
        "release_days_ahead": 30,
        "release_time_est": "10:00",
        "release_notes": "1-Michelin-star. Art gallery tasting menu. Intimate counter. 30-day Tock window.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/frevo",
    },
    {
        "restaurant_name": "Icca",
        "neighborhood": "Lower East Side",
        "cuisine": "Japanese Omakase",
        "booking_platform": "Tock",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "1-Michelin-star. Traditional Japanese omakase. 60-day Tock release.",
        "last_verified": TODAY,
        "source_url": "https://www.exploretock.com/icca",
    },
    {
        "restaurant_name": "I Sodi",
        "neighborhood": "West Village",
        "cuisine": "Tuscan Italian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Intimate Tuscan. 28-day midnight drop. Walk-in bar seats sometimes available.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/i-sodi",
    },
    {
        "restaurant_name": "Joji",
        "neighborhood": "Midtown East",
        "cuisine": "Japanese Omakase",
        "booking_platform": "Resy",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "2-Michelin-star. Omakase inside One Vanderbilt. 60-day Resy window. Joji Bar easier.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/joji",
    },
    {
        "restaurant_name": "Le Coucou",
        "neighborhood": "SoHo",
        "cuisine": "Classic French",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Daniel Boulud-adjacent classic French. 28-day midnight drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/le-coucou",
    },
    {
        "restaurant_name": "Shota Omakase",
        "neighborhood": "Williamsburg",
        "cuisine": "Japanese Sushi Omakase",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Brooklyn omakase. 30-day drop. Small counter seating.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/shota-omakase",
    },
    {
        "restaurant_name": "Nōksu",
        "neighborhood": "Midtown",
        "cuisine": "Contemporary Seafood Tasting Menu",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "10:00",
        "release_notes": "1-Michelin-star seafood counter. 30-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/noksu",
    },
    {
        "restaurant_name": "Corima",
        "neighborhood": "Lower East Side",
        "cuisine": "Modern Northern Mexican",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Contemporary Baja/Northern Mexican tasting menu. 28-day drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/corima",
    },
    {
        "restaurant_name": "The Four Horsemen",
        "neighborhood": "Williamsburg",
        "cuisine": "Contemporary American (Natural Wine Bar)",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. James Murphy (LCD Soundsystem) natural wine bar. 28-day drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/the-four-horsemen",
    },
    {
        "restaurant_name": "Francie",
        "neighborhood": "Williamsburg",
        "cuisine": "French-Italian Brasserie",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Williamsburg brasserie. 28-day midnight drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/francie",
    },
    {
        "restaurant_name": "Claud",
        "neighborhood": "East Village",
        "cuisine": "Contemporary European",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star French-leaning East Village spot. 28-day midnight drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/claud",
    },
    {
        "restaurant_name": "Le Crocodile",
        "neighborhood": "Williamsburg",
        "cuisine": "French Brasserie",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Williamsburg French brasserie. 28-day drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/le-crocodile",
    },
    {
        "restaurant_name": "Wildair",
        "neighborhood": "Lower East Side",
        "cuisine": "Contemporary American (Natural Wine)",
        "booking_platform": "OpenTable",
        "release_days_ahead": 28,
        "release_time_est": "09:00",
        "release_notes": "1-Michelin-star LES natural wine bar. 28-day window. Bar walk-ins accepted.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/r/wildair-new-york",
    },
    {
        "restaurant_name": "Coqodaq",
        "neighborhood": "Flatiron",
        "cuisine": "Korean Fried Chicken",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Korean fried chicken temple. 28-day midnight drop; extremely competitive.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/coqodaq",
    },
    {
        "restaurant_name": "Bungalow",
        "neighborhood": "West Village",
        "cuisine": "Modern Indian",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Regional pan-India tasting menu. 28-day drop. Very popular with Indian food lovers.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/bungalow-nyc",
    },
    {
        "restaurant_name": "The Corner Store",
        "neighborhood": "SoHo",
        "cuisine": "Contemporary American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Nobu Matsuhisa and Richie Akiva project. 28-day drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/the-corner-store",
    },
    {
        "restaurant_name": "The Polo Bar",
        "neighborhood": "Midtown East",
        "cuisine": "American (Classic Clubhouse)",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Ralph Lauren's see-and-be-seen dining room. 28-day Resy drop; very competitive for prime times.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/the-polo-bar",
    },
    {
        "restaurant_name": "Gage & Tollner",
        "neighborhood": "Downtown Brooklyn",
        "cuisine": "American Chophouse (Historic Revival)",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "Historic 1879 Brooklyn restaurant revived. 30-day OpenTable window.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/r/gage-and-tollner-brooklyn",
    },
    {
        "restaurant_name": "Atoboy",
        "neighborhood": "Flatiron",
        "cuisine": "Modern Korean",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Sister to Atomix; more accessible but still competitive. 28-day drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/atoboy",
    },
    {
        "restaurant_name": "Mari",
        "neighborhood": "West Village",
        "cuisine": "Modern Korean",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Korean tasting menu. 28-day midnight drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/mari-nyc",
    },
    {
        "restaurant_name": "Le Pavillon",
        "neighborhood": "Midtown East",
        "cuisine": "Vegetable-Focused French",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "1-Michelin-star. Daniel Boulud vegetable-focused concept. 30-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/le-pavillon",
    },
    {
        "restaurant_name": "Restaurant Yuu",
        "neighborhood": "Williamsburg",
        "cuisine": "French-Japanese Fusion",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "10:00",
        "release_notes": "1-Michelin-star. French-Japanese tasting menu. Small counter. 30-day Resy drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/restaurant-yuu",
    },
    {
        "restaurant_name": "Tempura Matsui",
        "neighborhood": "Midtown East",
        "cuisine": "Japanese Tempura Omakase",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "1-Michelin-star. Counter tempura omakase. 30-day OpenTable window.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/r/tempura-matsui-new-york",
    },
    {
        "restaurant_name": "Tsukimi",
        "neighborhood": "East Village",
        "cuisine": "Japanese Kaiseki",
        "booking_platform": "OpenTable",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "1-Michelin-star. Counter kaiseki omakase. 30-day OpenTable window.",
        "last_verified": TODAY,
        "source_url": "https://www.opentable.com/r/tsukimi-new-york",
    },
    {
        "restaurant_name": "Yamada",
        "neighborhood": "Midtown East",
        "cuisine": "Japanese Kaiseki",
        "booking_platform": "Resy",
        "release_days_ahead": 60,
        "release_time_est": "10:00",
        "release_notes": "1-Michelin-star. Authentic Japanese kaiseki counter. 60-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/yamada-nyc",
    },
    {
        "restaurant_name": "Marea",
        "neighborhood": "Midtown West",
        "cuisine": "Italian Seafood",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "09:00",
        "release_notes": "2-Michelin-star Italian seafood. 30-day Resy window. Lunch often easier than dinner.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/marea",
    },
    {
        "restaurant_name": "Jeju Noodle Bar",
        "neighborhood": "West Village",
        "cuisine": "Korean Ramen",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Korean ramen. Very small (30 seats). 28-day midnight drop; notoriously hard to book.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/jeju-noodle-bar",
    },
    {
        "restaurant_name": "Le Veau d'Or",
        "neighborhood": "Upper East Side",
        "cuisine": "Classic French Bistro",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Revived 1937 UES French classic by Lee Hanson and Riad Nasr. 28-day drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/le-veau-dor",
    },
    {
        "restaurant_name": "Sushi Katsuei",
        "neighborhood": "Park Slope",
        "cuisine": "Japanese Sushi Omakase",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star Brooklyn sushi omakase. 28-day drop. Counter seats only.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/sushi-katsuei",
    },
    {
        "restaurant_name": "Il Buco",
        "neighborhood": "NoHo",
        "cuisine": "Italian-Mediterranean (Rustic)",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Beloved NoHo Italian since 1994. 28-day drop. Very popular for special occasions.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/il-buco",
    },
    {
        "restaurant_name": "Muku",
        "neighborhood": "Midtown West",
        "cuisine": "Japanese Kaiseki",
        "booking_platform": "Resy",
        "release_days_ahead": 30,
        "release_time_est": "10:00",
        "release_notes": "1-Michelin-star kaiseki. 30-day Resy window. Counter seating.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/muku-nyc",
    },
    {
        "restaurant_name": "The Grill",
        "neighborhood": "Midtown East",
        "cuisine": "American Continental",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Inside the Seagram Building. Power lunch scene. 28-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/the-grill",
    },
    {
        "restaurant_name": "Naro",
        "neighborhood": "NoMad",
        "cuisine": "Modern Korean",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Contemporary Korean tasting menu. 28-day midnight Resy drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/naro",
    },
    {
        "restaurant_name": "Sailor",
        "neighborhood": "Carroll Gardens",
        "cuisine": "Contemporary American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Brooklyn neighborhood favorite. 28-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/sailor",
    },
    {
        "restaurant_name": "Tuome",
        "neighborhood": "East Village",
        "cuisine": "Contemporary Asian-American",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "1-Michelin-star. Contemporary Asian-American. 28-day Resy window.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/tuome",
    },
    {
        "restaurant_name": "Lucali",
        "neighborhood": "Carroll Gardens",
        "cuisine": "Neapolitan Pizza",
        "booking_platform": "Resy",
        "release_days_ahead": 14,
        "release_time_est": "10:00",
        "release_notes": "Now on Resy (walk-in waitlist). Also accepts walk-ins from 4pm. Cash only. Closed Tuesdays. 14-day online window but walk-in remains the classic approach.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/lucali",
    },
    {
        "restaurant_name": "Minetta Tavern",
        "neighborhood": "Greenwich Village",
        "cuisine": "French-American Bistro",
        "booking_platform": "Resy",
        "release_days_ahead": 28,
        "release_time_est": "00:00",
        "release_notes": "Keith McNally brasserie. Black Label Burger famous. Now on Resy. 28-day midnight drop.",
        "last_verified": TODAY,
        "source_url": "https://resy.com/cities/ny/venues/minetta-tavern",
    },
]

# Deduplicate by restaurant_name (keep last occurrence)
seen = {}
for r in RESTAURANTS:
    seen[r["restaurant_name"]] = r
RESTAURANTS = list(seen.values())


def write_csv(rows, filepath, fieldnames):
    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {len(rows)} rows to {filepath}")


def main():
    results = []
    manual = []

    for r in RESTAURANTS:
        row = {k: r.get(k, "") for k in FIELDNAMES}
        if row["release_days_ahead"] is None:
            row["release_days_ahead"] = ""
        results.append(row)

        # Flag walk-in / phone / email to manual review
        if row["booking_platform"] in ("Walk-in", "Phone", "Email") or row["release_days_ahead"] == "":
            manual_row = {**row, "reason": "Manual release schedule — no automated booking platform"}
            manual.append(manual_row)

    write_csv(results, RESTAURANTS_CSV, FIELDNAMES)
    write_csv(manual, MANUAL_CSV, MANUAL_FIELDNAMES)
    print(f"Done: {len(results)} restaurants, {len(manual)} flagged for manual review.")


if __name__ == "__main__":
    main()
